---
# Add system users for default Dovecot authorization
- user: name={{ item.name }} comment="Dovecot user" password={{ item.password }}
  with_items: postfix_users


- include: postfix.yml
- include: dovecot.yml
- include: smtpd.yml
- include: sasl.yml

